---
#
# Ansible managed
#
repository:
  description: Basic CentOS Configuration
  homepage: https://buluma.github.io/
  topics: centos, postinstalltweaks, system, security, fail2ban, development, ansible, molecule, tox, playbook
