---
- name: Sshd restart
  ansible.builtin.service: name=sshd state=restarted

- name: Firewalld restart
  ansible.builtin.service: name=firewalld state=restarted

- name: Fail2ban restart
  ansible.builtin.service: name=fail2ban state=restarted
