---
# TODO move this playbook to a different scenario
# Default scenario must work with default variable values
- name: Converge
  hosts: all
  vars:
    - centos_base_utility_packages: true
    - centos_base_enable_epel: true
    - centos_base_secure_sshd: true
    - centos_base_vim_users: ['root']
    - centos_base_basic_vim_tweaks: true
    - centos_base_firewalld_services: ['http']
    - centos_base_basic_packages: true
    - centos_base_firewalld: true
    - centos_base_debug_packages: true
    - centos_base_security_packages: true
    - centos_base_development_packages: true
    - centos_base_selinux_packages: true
    - centos_base_lockprg: true
    - centos_base_htop_configuration: true
    - centos_base_fail2ban_configuration: true
  pre_tasks:
    - name: intall Apache
      ansible.builtin.yum:
        name: httpd
    - name: start httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
  roles:
    - role: buluma.centos_base
